MAX_RECV_SIZE = 2048 # Maximum bytes sent over single TCP packet
DEFAULT_SERVER_PORT = 12345 
DEFAULT_SERVER_ADDRESS = '' 

# Game states
GAME_STATE_MID_ROUND = 0
GAME_STATE_ROUND_CATCH = 1
GAME_STATE_OVER = 2