# JSON Keys
KEY_JSON_MESSAGE = "message"
KEY_JSON_PLAYER_ID = "id"
KEY_JSON_PLAYER_SCORE = "score"
KEY_JSON_PLAYER_HAND = "hand"
KEY_JSON_PLAYER_DRAFT = "draft"
KEY_JSON_DETAILS = "details"
KEY_JSON_GAMESTATE = "state"
KEY_JSON_ROUND_NUMBER = "roundnumber"
KEY_JSON_ROUND_TOTAL = "roundtotal"
KEY_JSON_OTHER_PLAYER_DATA = "otherplayers"
KEY_JSON_OTHER_PLAYER_DRAFT = "otherplayerdraft"
KEY_JSON_OTHER_PLAYER_SCORE = "otherplayerscore"
KEY_JSON_WINNER_ID = "winnerid"
KEY_JSON_ACTIVITY_LIST = "activitylist"
KEY_JSON_ACTIVITY_USED = "activityused"
KEY_JSON_PLAYER_RETURN_DICT = "responsetoplayer" # used in server to route return info to clients